<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQantjuj\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQantjuj/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerQantjuj.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerQantjuj\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerQantjuj\appDevDebugProjectContainer([
    'container.build_hash' => 'Qantjuj',
    'container.build_id' => '11840578',
    'container.build_time' => 1578324478,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQantjuj');
